version: "3.7"
services:
  dotnet_api:
    build:
      context: src/
      dockerfile: VAF13.Klubadmin.API/Dockerfile
    container_name: dotnet_api
    env_file: .env
    ports:
      - "8080:8080"
  go_api:
    build:
      context: v2src/
      dockerfile: Dockerfile
    container_name: go_api
    env_file: .env
    ports:
      - "8085:8080"