version: "3.7"
services:
  dotnet_api:
    build:
      context: src/
      dockerfile: VAF13.Klubadmin.API/Dockerfile
    container_name: dotnet_api
    env_file: .env
    ports:
      - "8080:8080"
  go_api:
    build:
      context: v2src/
      dockerfile: Dockerfile
    container_name: go_api
    env_file: .env
    ports:
      - "8085:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - 8099:80
    volumes:
      - ./spec/:/spec
    environment:
      - SWAGGER_JSON=/spec/openapi_spec.json
      - PORT=80